### PR TITLE
Migration of ADB Connector Assets

### PR DESCRIPTION
**Pull request by bhenndricks**
Need to test functionality of github.io links.

### CODE REVIEW

**Review by rrumale — CHANGES_REQUESTED** [review]
please check the path for datastage.md file in manifest file.  Also the foldername and filename have to be the same.

**Comment by rrumale** [comment]
Hello Blake
Please check the filenames. I see one file with caps PNG in it
Also the path to the datastage.md file is not correct
please check if the IO pages are rendering correctly in your fork
I think there is an issue with the file path in tableau also.  
Please do the corrections and resubmit the PR.

**Comment by bhenndricks** [comment]
Making changes now. Let me know if this works better. Can not test io url until links are published.

**Comment by bhenndricks** [comment]
In general, file extensions are not case sensitive on most operating systems. This means that whether a file extension is written in uppercase or lowercase letters does not affect the file's functionality or compatibility with software applications.

**Pull request closed without merging**
